### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by vidyahari** [urigoren/conjugate_prior#3]
Hi,

I'm trying to install conjugate-prior using the command 'pip3 install conjugate-prior'

But it resulted in an error
Using cached conjugate_prior-0.38.tar.gz (4.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lauso1xv/conjugate-prior/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lauso1xv/conjugate-prior/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-foq_3pxz
         cwd: /tmp/pip-install-lauso1xv/conjugate-prior/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lauso1xv/conjugate-prior/setup.py", line 3, in <module>
        with open(__file__.replace("setup.py", "README.md"), 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-lauso1xv/conjugate-prior/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

my pip and supported files are upgraded and is up-to-date.
Its showing setup.py file is missing.
Please help to resolve this issue

Thanks in advance

Vidya
9446482122

**Comment by urigoren** [comment]
Thank you, fixed it.

could you please verify that it works now ?
`pip install --upgrade conjugate_prior`

**Comment by vidyahari** [comment]
Thank you.

Now the error is resolved and is installed properly
