### ISSUE TITLE
Normalnormal model issues

### ISSUE THREAD

**Issue by dmasip-rxd** [urigoren/conjugate_prior#4]
Hi, thanks for a useful package. I think there are a couple of bugs in the normalnormal model.

I think this line should be deleted.

https://github.com/urigoren/conjugate_prior/blob/b1589cdcd98b0512ae6b654c2f949305dbedc2de/conjugate_prior/normal.py#L22

I think these should calculate density functions as the `sample` and `predict` methods
https://github.com/urigoren/conjugate_prior/blob/b1589cdcd98b0512ae6b654c2f949305dbedc2de/conjugate_prior/normal.py#L30-L34

That is, something like

```
    def pdf(self, x):
        return stats.norm.pdf(x, self.mean, np.sqrt(self.var + self.known_var))

    def cdf(self, x):
        return stats.norm.cdf(x, self.mean, np.sqrt(self.var + self.known_var))
```

also, square roots have to be applied in all the `stats.norm` methods, as the input parameter in there is the standard deviation, not the variance.

**Comment by urigoren** [comment]
You are absolutely right, thank you for the issue.
I have fixed the errors you mentioned, thank you so much for letting me know
